version: '3.8'

name: base

networks:
  base:
    name: base
    driver: bridge

services:
  database:
    container_name: energy-bill-api-db
    image: postgres
    ports:
      - 5432:5432
    networks:
      - base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  backend:
    container_name: energy-bill-api
    image: energy-bill-api
    build: .
    ports:
      - 3000:3000
    networks:
      - base
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env